version: '3.1'

# Specify docker-compose file with: -f <compose-file.yml>

services:
  mysql:
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:  # Use root/example as user/password
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  fitness:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=docker-test
    volumes:
      - ./:/home/node/app
    ports:
      - 3002:3003
    depends_on:
      - mysql
    command: ["./wait-for-it.sh","mysql:3306","--","npm","run-script","docker-test"]

