version: '3.1'
services:
  mysql:
    image: mysql
    command:
      --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:  # Use root/example as user/password
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  fitness:
    # TODO: How to wait for the mysql service?
    image: "node:8"
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=docker-test
    volumes:
      - ./:/home/node/app
    ports:
      - 3002:3003
    command: "npm docker-test"

